abstract class AppRoutes {
  AppRoutes._();
  static const HOME = _Paths.HOME;
  static const AUTH = _Paths.AUTH;
  static const LOGIN = _Paths.LOGIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const ASSIGNMENT = _Paths.ASSIGNMENT;
  static const SELECT_VEHICLE = _Paths.SELECT_VEHICLE;
  static const SELECT_TRAILER = _Paths.SELECT_TRAILER;
  static const ENTER_TRAILER = _Paths.ENTER_TRAILER;
  static const SELECT_SHIPPING = _Paths.SELECT_SHIPPING;
  static const ENTER_SHIPPING = _Paths.ENTER_SHIPPING;
  static const HOS = _Paths.HOS;
  static const DVIR = _Paths.DVIR;
  static const ROUTES = _Paths.ROUTES;
  static const FORMS = _Paths.FORMS;
  static const FUELING = _Paths.FUELING;
  static const CO_DRIVER_LOGIN = _Paths.CO_DRIVER_LOGIN;
  static const SPLASH = _Paths.SPLASH;
  static const DAILY_LOG = _Paths.DAILY_LOG;
  static const SETTINGS = _Paths.SETTINGS;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const HELP = _Paths.HELP;
  static const CREATE_DVIR = _Paths.CREATE_DVIR;
  static const DRIVER_SWITCHING = _Paths.DRIVER_SWITCHING;
  static const ADD_DEFECT = _Paths.ADD_DEFECT;
  static const DOT_INSPECTION = _Paths.DOT_INSPECTION;
  static const DOT_INSPECTION_DETAIL = _Paths.DOT_INSPECTION_DETAIL;
  static const ACCESS_CODE = _Paths.ACCESS_CODE;
  static const SEND_ELD_DATA = _Paths.SEND_ELD_DATA;
  static const SEND_LOGS = _Paths.SEND_LOGS;
  static const NOTIFICATION = _Paths.NOTIFICATION;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const AUTH = '/auth';
  static const LOGIN = '/login';
  static const SIGNUP = '/signup';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const ASSIGNMENT = '/assignment';
  static const SELECT_VEHICLE = '/assignment/select-vehicle';
  static const SELECT_TRAILER = '/assignment/select-trailer';
  static const ENTER_TRAILER = '/assignment/enter-trailer';
  static const SELECT_SHIPPING = '/assignment/select-shipping';
  static const ENTER_SHIPPING = '/assignment/enter-shipping';
  static const HOS = '/hos';
  static const DVIR = '/dvir';
  static const ROUTES = '/routes';
  static const FORMS = '/forms';
  static const FUELING = '/fueling';
  static const CO_DRIVER_LOGIN = '/co-driver-login';
  static const SPLASH = '/splash';
  static const DAILY_LOG = '/daily-log';
  static const SETTINGS = '/settings';
  static const EDIT_PROFILE = '/edit-profile';
  static const DASHBOARD = '/dashboard';
  static const HELP = '/help';
  static const CREATE_DVIR = '/create_dvir';
  static const DRIVER_SWITCHING = '/driver_switching';
  static const ADD_DEFECT = '/add-defect';
  static const DOT_INSPECTION = '/dot-inspection';
  static const DOT_INSPECTION_DETAIL = '/dot-inspection-detail';
  static const ACCESS_CODE = '/access-code';
  static const SEND_ELD_DATA = '/send-eld-data';
  static const SEND_LOGS = '/send-logs';
  static const NOTIFICATION = '/notification';
}
